[project]
name = "quantdairy"
version = "0.0.1"
description = "quantdairy"
authors = [
  { name = "quantdairy", email = "21pradipjadhav@gmail.com" }
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = []

[tool.frappe]
app_name = "quantdairy"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
